version: "3.3"
services:
  movies-db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
  clients:
    build: ./clients
    ports:
      - "8000:80"
    volumes:
      - ./clients:/app
    depends_on:
      - movies-db
