version: "3.3"
services:
  clients-db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  users-db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"

  clients:
    build: ./clients
    ports:
      - "8000:8000"
    volumes:
      - ./clients:/app
    depends_on:
      - clients-db

  users:
    build: ./users
    ports:
      - "8001:8000"
    volumes:
      - ./users:/app
    depends_on:
      - users-db
